language: java
jdk:
- oraclejdk8
script:
- mvn verify
after_success:
- |
  if [ "$TRAVIS_BRANCH" = 'master' ] || [ -n "$TRAVIS_TAG" ]; then \
    openssl aes-256-cbc -K $encrypted_c0b30b790a3a_key -iv $encrypted_c0b30b790a3a_iv -in ci/signing.asc.enc -out ci/signing.asc -d && \
    gpg2 --import ci/signing.asc && \
    mvn deploy -P sign --settings ci/settings.xml
  fi
notifications:
  email:
    recipients:
    - victor.gonzalez@geomati.co
  on_success: always
